language: php
php:
  - 7.1
  - 7.2
  - 7.3
sudo: false
install:
  - yes '' | pecl install -f swoole
  - composer install
before_script:
  - if [ $TRAVIS_PHP_VERSION != '7.3' ]; then phpenv config-rm xdebug.ini; fi;
  - pushd public
  - php index.php &
  - popd
  - sleep 4
script:
  - DB=sqlite SEND=external vendor/bin/phpunit
